### PR TITLE
HTML Form

### PR DESCRIPTION
**Pull request by Tahirbhalli**
Finalized the HTML Form Project by updating the Readme.md file and also adding the gitignore file

### CODE REVIEW

**Comment by euqueme** [comment]
## Pull Request under the review by Maria Eugenia Quemé P. (TSE)

**Comment by euqueme** [comment]
> ## Pull Request under the review by Maria Eugenia Quemé P. (TSE)

### Hello @Tahirbhalli  and @java-cromium: Theres a mandatory request before we can go ahead with the review
[Mandatory] Please set up a code linter as requested in the [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/)

#### When that's done kindly :pray: submit a code review again.

**Review by fatymahmed — COMMENTED** [review]
## Hi @Tahirbhalli  @java-cromium,
Your project looks good, great job 👏👏.
However, there are a couple of things that you need to fix.
- Please fix stickler errors, you can view the errors by clicking on checks in your pull request, see screenshot below.
screenshot

- I noticed that you committed DS_Store, please remove this file by adding it to your .gittigore file then remove it from cache by following [this](https://stackoverflow.com/questions/1274057/how-to-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore), [see screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png)  of the requirement from Pathwright.

- Please use a `<form> ` tag for your form, [see screenshot of requirement from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/html_forms/form_and_input_requirement.png)
- Update your live link in your README file, the current one doesn't work.
[OPTIONAL]
- I highly encourage you to use a font similar to the one in [mint page](https://accounts.intuit.com/signup.html)

**Review by fatymahmed — CHANGES_REQUESTED** [review]
### Kindly make the suggested changes then request for a code review.
## Status: Changes Required

_Feel free to reach out to me on slack(Fatima) if you have any questions, I'd be happy to help_

**Review by fatymahmed — APPROVED** [review]
## Hi @Tahirbhalli @java-cromium,
It's a 👍🏾 from me!
## ✔️ Approved!

Good luck with your next projects.
_Don't forget to submit your project completion form_

**Pull request merged**
